apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: chupacabra
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: monitoring
spec: {}
status: {}